# This is a basic workflow to help you get started with Actions

name: JS Actions

# Controls when the action will run. 
on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
